plugins {
    id 'com.android.application'
}

android {
    namespace 'com.markos.vpn'
    compileSdk 30

    defaultConfig {
        applicationId "com.markos.vpn"
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
